spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/caed?schema=caed
    username: postgres
    password: debian23

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG